Abc.Mvc/Abc.Mvc/Controllers/SiparislerimController.cs
using Abc.Mvc.Entity;
using Abc.Mvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Abc.Mvc.Controllers
{
    public class SiparislerimController : Controller
    {
        private DataContext db = new DataContext();
        // GET: Siparislerim
        public ActionResult Index()
        {
             var userName = Session["UserId"] as string;

            if (string.IsNullOrEmpty(userName))
            {

                return RedirectToAction("Login", "Account");
            }

            var siparislerim = db.Orders
                                  .Where(s => s.Username == userName)
                                  .ToList();

            return View(siparislerim);
        }

        public ActionResult iptal(int id)
        {
            var siparis = db.Orders.Find(id);

            if(siparis.OrderState == EnumOrderState.Waiting)
            {
                db.Orders.Remove(siparis);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                TempData["ErrorMessage"] = "Siparişi iptal edemezsiniz. Sipariş durumu uygun değil.";
                return RedirectToAction("Index");

            }

          


           
        }


        public ActionResult Detay(int id)
        {
        //    var detay = db.Orders.FirstOrDefault(i => i.Id == id);

        //    return View(detay);

              var entity = db.Orders.Where(i => i.Id == id)
                .Select(i => new OrderDetailsModel()
                {
                    OrderId = i.Id,
                    UserName = i.Username,
                    OrderNumber = i.OrderNumber,
                    Total = i.Total,
                    OrderDate = i.OrderDate,
                    OrderState = i.OrderState,
                    AdresBasligi = i.AdresBasligi,
                    Adres = i.Adres,
                    Sehir = i.Sehir,
                    Semt = i.Semt,
                    Mahalle = i.Mahalle,
                    PostaKodu = i.PostaKodu,
                    Orderlines = i.OrderLines.Select(a => new OrderLineModel()
                    {
                        ProductId = a.ProductId,
                        ProductName = a.Product.Name.Length > 50 ? a.Product.Name.Substring(0, 47) + "..." : a.Product.Name,
                        Image = a.Product.Image,
                        Quantity = a.Quantity,
                        Price = a.Price
                    }).ToList()
                }).FirstOrDefault();

            return View(entity);




    }



    }
}

Abc.Mvc/Abc.Mvc/Views/Siparislerim/Detay.cshtml
@model Abc.Mvc.Models.OrderDetailsModel

@{
    ViewBag.Title = "Detay";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h1>Sipariş Detayı</h1>

<dl class="row">
    <dt class="col-sm-3">Kullanıcı Adı</dt>
    <dd class="col-sm-9">@Model.UserName</dd>

    <dt class="col-sm-3">Sipariş Numarası</dt>
    <dd class="col-sm-9">@Model.OrderNumber</dd>

    <dt class="col-sm-3">Toplam Tutar</dt>
    <dd class="col-sm-9">
        <i class="fa fa-try" aria-hidden="true"></i>
        @Model.Total
    </dd>

    <dt class="col-sm-3">Sipariş Tarihi</dt>
    <dd class="col-sm-9">@Model.OrderDate.ToString("dd/MM/yyyy")</dd>

    <dt class="col-sm-3">Adres Bilgisi</dt>
    <dd class="col-sm-9">
        @Model.AdresBasligi
        <br />
        @Model.Adres
        <br />
        @Model.Sehir - @Model.Semt - @Model.Mahalle
        <br />
        @Model.PostaKodu
    </dd>

    <dt class="col-sm-3">Ürünler</dt>
    <dd class="col-sm-9">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Ürün Resmi</th>
                    <th>Ürün Adı</th>
                    <th>Adet</th>
                    <th>Fiyat</th>
                    <th>Toplam</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Orderlines)
                {
                    <tr>
                        <td><img src="/Upload/@item.Image" width="70" /></td>
                        <td>@item.ProductName</td>
                        <td>@item.Quantity</td>
                        <td>
                            <i class="fa fa-try" aria-hidden="true"></i>
                            @item.Price
                        </td>
                        <td>
                            <i class="fa fa-try" aria-hidden="true"></i>
                            @(item.Price * item.Quantity)
                        </td>
                        <td>
                            <a href="/Home/Details/@item.ProductId" class="btn btn-primary btn-sm" target="_blank">
                                <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                                Ürün Detayı
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </dd>
</dl>

Abc.Mvc/Abc.Mvc/Views/Siparislerim/Index.cshtml
@model IEnumerable<Abc.Mvc.Entity.Order>

@{
    ViewBag.Title = "Siparişlerim";
}

<h2>Siparişlerim</h2>

@if (Model != null && Model.Any())
{

    if (TempData["ErrorMessage"] != null)
    {
        <script>
        alert('@TempData["ErrorMessage"]');
        </script>
    }


    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Sipariş Numarası</th>
                <th>Sipariş Tarihi</th>
                <th>Toplam Tutar</th>
                <th>Durum</th>
                <th>Sipariş İşlemleri</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var order in Model)
            {
                <tr>
                    <td>@order.OrderNumber</td>
                    <td>@order.OrderDate.ToString("dd/MM/yyyy")</td>
                    <td>@order.Total.ToString("C")</td>
                    <td>@order.OrderState</td>
                    <td>
                        <a href="@Url.Action("Detay", "Siparislerim", new { id = order.Id })" class="btn btn-primary btn-sm float-right">
                            <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                            Detay İncele
                        </a>
                        <a href="@Url.Action("iptal", "Siparislerim", new { id = order.Id })" class="btn btn-danger btn-sm float-right">
                            <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                            Siparişi İptal Et
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Henüz siparişiniz bulunmamaktadır.</p>
}