Abc.Mvc/Abc.Mvc/Controllers/CommentController.cs
using Abc.Mvc.Entity;
using Abc.Mvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Abc.Mvc.Controllers
{
    public class CommentController : Controller
    {
        DataContext _context = new DataContext();
        // GET: Comment
        public ActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public ActionResult AddedComment()
        {
            
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddedComment(string UserComment)
        {
            if (string.IsNullOrWhiteSpace(UserComment))
            {
                TempData["ErrorMessageComment"] = "Bu alan boş bırakılamaz!";
                return View();
            }


            else
            {
                var comment = new Comment()
                {
                    UserId = Session["UserId"] as string,
                    ProductId = Convert.ToInt32(Session["id"]),
                    UserComment = UserComment       
                };
                var productId = comment.ProductId;
                _context.Comments.Add(comment);
                _context.SaveChanges();
                return RedirectToAction("Details", "Home", new { id = productId });

            }
            return View();
        }

        public ActionResult DeleteComment(int commentId)
        {
            var comment = _context.Comments.FirstOrDefault(i => i.Id == commentId);
            var productId = comment.ProductId;
            _context.Comments.Remove(comment);
            _context.SaveChanges();

          

            return RedirectToAction("Details","Home", new { id = productId });
        }



    }
}

Abc.Mvc/Abc.Mvc/Controllers/HomeController.cs
using Abc.Mvc.Entity;
using Abc.Mvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Abc.Mvc.Controllers
{
    public class HomeController : Controller
    {

        DataContext _context = new DataContext();
        // GET: Home

        public ActionResult Index()
        {

           
            var userId = User.Identity.Name; // veya uygun bir kullanıcı ID'si

            // 1. Adım: Veritabanından ürünleri çek
            var urunler = _context.Products
                .Where(i => i.IsHome && i.IsApproved)
                .Select(i => new
                {
                    Id = i.Id,
                    Name = i.Name.Length > 50 ? i.Name.Substring(0, 47) + "..." : i.Name,
                    Description = i.Description.Length > 50 ? i.Description.Substring(0, 47) + "..." : i.Description,
                    Price = i.Price,
                    Stock = i.Stock,
                    Image = i.Image,
                    CategoryId = i.CategoryId
                })
                .ToList();

            // 2. Adım: Favori ürünler listesini al
            var favoriteProductIds = _context.Favorites
                .Where(f => f.UserId == userId)
                .Select(f => f.productId)
                .ToList();

            // 3. Adım: Anonim türlerden ProductModel nesnelerine dönüştürme
            var productModels = urunler
                .Select(i => new ProductModel
                {
                    Id = i.Id,
                    Name = i.Name,
                    Description = i.Description,
                    Price = i.Price,
                    Stock = i.Stock,
                    Image = i.Image,
                    CategoryId = i.CategoryId,
                    IsFavorite = favoriteProductIds.Contains(i.Id) // Favori kontrolü
                })
                .ToList();

            return View(productModels);
        }
        public ActionResult Details(int id)
        {

            Session["id"] = id ;
            //return View(_context.Products.Where(i => i.Id==id).FirstOrDefault());

            var product = _context.Products.FirstOrDefault(i => i.Id == id);
            var comments = _context.Comments.Where(c => c.ProductId == id).ToList();

            var viewModel = new DetailsComment
            {
                Product = product,
                Comment = comments,
                
            };




            return View(viewModel);
        }
      
        public ActionResult List(int? id)
        {

          
            var userId = User.Identity.Name; // veya uygun bir kullanıcı ID'si
            var urunler = _context.Products
            .Where(i => i.IsApproved);

            if (id != null)
            {
                urunler = urunler.Where(i => i.CategoryId == id);
            }
            var favoriteProductIds = _context.Favorites
              .Where(f => f.UserId == userId)
              .Select(f => f.productId)
              .ToList();
            // Sorguyu tamamlayıp veriyi belleğe çekiyoruz
            var urunlerList = urunler.ToList();

            // Veriyi aldıktan sonra, ViewModel'e dönüştürüyoruz
            var viewModel = urunlerList.Select(i => new ProductModel()
            {
                Id = i.Id,
                Name = i.Name.Length > 50 ? i.Name.Substring(0, 47) + "..." : i.Name,
                Description = !string.IsNullOrEmpty(i.Description)
                              ? (i.Description.Length > 50 ? i.Description.Substring(0, 47) + "..." : i.Description)
                              : "No description available.",
                Price = i.Price,
                Stock = i.Stock,
                Image = i.Image ?? "1.jpg",
                CategoryId = i.CategoryId,
                IsFavorite = favoriteProductIds.Contains(i.Id)

            }).AsQueryable();

            return View(viewModel.ToList());
        }


        public PartialViewResult GetCategories()
        {
            return PartialView(_context.Categories.ToList());
        }





    }
}

Abc.Mvc/Abc.Mvc/Controllers/SepetController.cs
using Abc.Mvc.Entity;
using Abc.Mvc.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Abc.Mvc.Controllers
{
    public class SepetController : Controller
    {
        private DataContext db = new DataContext();

        [Authorize]
        public ActionResult Index()
        {
            var userName = Session["UserId"] as string;

            if (string.IsNullOrEmpty(userName))
            {
                return View(new List<ProductModel>());
            }

           
            var sepetUrunleri = db.Sepet
                                  .Where(s => s.UserName == userName)
                                  .GroupBy(s => s.ProductId)
                                  .Select(g => new
                                  {
                                      ProductId = g.Key, 
                                      Quantity = g.Sum(s => s.Quantity)  
                                  })
                                  .ToList();

         
            var sepetViewModel = sepetUrunleri
                .Select(u => {
                    var product = db.Products.FirstOrDefault(p => p.Id == u.ProductId);

                    return new ProductModel
                    {
                        Id = product.Id,
                        Name = product.Name,
                        Description = product.Description,
                        Price = product.Price,
                        Stock = product.Stock,
                        Image = product.Image,
                        CategoryId = product.CategoryId,
                        Quantity = u.Quantity  
                    };
                })
                .ToList();

            
            if (sepetViewModel.Count != 0)
            {
                double totalPrice = sepetViewModel.Sum(p => p.Price * p.Quantity);
                ViewBag.TotalPrice = totalPrice;
            }

            return View(sepetViewModel);
        }

        [HttpPost]
        public ActionResult AddSepet(int id)
        {
            var userName = Session["UserId"] as string;

          
            var existingProduct = db.Sepet
                                    .FirstOrDefault(s => s.ProductId == id && s.UserName == userName);

            if (existingProduct != null)
            {
                existingProduct.Quantity += 1;
            }
            else
            {
                var product = db.Products.FirstOrDefault(i => i.Id == id);

                if (product != null)
                {
                    var sepet = new Sepet
                    {
                        UserName = userName,
                        ProductId = product.Id, 
                        Quantity = 1 
                    };

                    db.Sepet.Add(sepet);
                }
            }

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult RemoveSepet(int id)
        {
          
            var userId = Session["UserId"] as string;

           
            var sepet = db.Sepet
                .FirstOrDefault(f => f.UserName == userId && f.ProductId == id);

            if (sepet != null)
            {
                if (sepet.Quantity > 1)
                {
                   
                    sepet.Quantity -= 1;
                }
                else
                {
                    
                    db.Sepet.Remove(sepet);
                }

                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ActionResult Checkout(ShippingDetails entity)
        {
           
            var userName = Session["UserId"] as string;

            if (string.IsNullOrEmpty(userName))
            {
                
                return RedirectToAction("Login", "Account");
            }

          
            var cart = db.Sepet
                          .Where(s => s.UserName == userName)
                          .ToList();

           
            if (cart.Count == 0)
            {
                ModelState.AddModelError("UrunYokError", "Sepetinizde ürün yok!");
                return View(entity);
            }

            if (ModelState.IsValid)
            {
               
                SaveOrder(cart, entity);

               
                db.Sepet.RemoveRange(cart);
                db.SaveChanges();

               
                return View("Completed");
            }
            else
            {
                
                return View(entity);
            }
        }
        private void SaveOrder(List<Sepet> cart , ShippingDetails entity)
        {
            var order = new Order();
            order.OrderNumber = "A" + (new Random()).Next(111111, 999999).ToString();

         
            order.Total = cart.Sum(p => p.Product.Price * p.Quantity);

            order.OrderDate = DateTime.Now;
            order.OrderState = EnumOrderState.Waiting;
            order.Username = User.Identity.Name;

            order.AdresBasligi = entity.AdresBasligi;
            order.Adres = entity.Adres;
            order.Sehir = entity.Sehir;
            order.Semt = entity.Semt;
            order.Mahalle = entity.Mahalle;
            order.PostaKodu = entity.PostaKodu;
            order.OrderLines = new List<OrderLine>();

            foreach (var pr in cart)
            {
                var orderline = new OrderLine();
                orderline.Quantity = pr.Quantity;
                orderline.Price = pr.Product.Price; 
                orderline.ProductId = pr.ProductId;

                order.OrderLines.Add(orderline);
            }
            db.Orders.Add(order);
            db.SaveChanges();
        }








    }
}

Abc.Mvc/Abc.Mvc/Views/Home/Details.cshtml
@using Abc.Mvc.Models;
@model Abc.Mvc.Models.DetailsComment
@{
    ViewBag.Title = "Details";
}

<style>
    .btn-faild {
        background-color: red; /* Kırmızı arka plan rengi */
        color: white; /* Yazı rengini beyaz yap */
        border: none; /* Varsayılan sınırları kaldır */
        padding: 10px 20px; /* İç boşluk */
        font-size: 16px; /* Yazı boyutu */
        border-radius: 5px; /* Köşeleri yuvarla */
        cursor: pointer; /* Fare imlecini pointer yap */
    }

        .btn-faild:hover {
            background-color: darkred; /* Üzerine gelindiğinde daha koyu kırmızı */
        }
</style>
<div id="product-details" class="container pb-5">
    <div class="row">

        <div class="col-md-6">
            <img src="~/Upload/@Model.Product.Image" class="img-fluid rounded ">
        </div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12">
                    <h1>@Model.Product.Name</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    @if (Model.Product.IsApproved)
                    {
                        <span class="badge badge-primary">Stokta</span>
                    }
                    else
                    {
                        <span class="badge badge-danger">Stokta Yok</span>
                    }

                    <span class="product-number">#2365656</span>
                </div>
            </div>

            <div class="row mt-2">
                <div class="col-md-12">
                    <div id="description">
                        @Model.Product.Description
                    </div>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-4">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star" aria-hidden="true"></i>
                    <i class="fa fa-star-half-o" aria-hidden="true"></i>
                    <span class="badge badge-success">53</span>
                </div>
                <div id="write-review" class="col-md-4">
                    <a href="#">
                        Write a review
                    </a>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-md-12">
                    <h4 id="product-price"> @Model.Product.Price TL</h4>
                </div>

            </div>
            <div class="row mt-2">
                <div class="col-md-12">

                    @using (Html.BeginForm("AddSepet", "Sepet"))
                    {

              
                        <form method="post" action="@Url.Action("AddSepet", "Sepet")">
                            @Html.Hidden("id", @Model.Product.Id)
                            <button type="submit" class="btn btn-success">
                                <i class="fa fa-cart-plus" aria-hidden="true"></i>
                                Add To Cart
                            </button>
                        </form>
                    }


                </div>
            </div>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-md-12">
            <div class="bd-example bd-example-tabs">
                <ul class="nav nav-tabs mb-3" id="pills-tab" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" id="pills-description-tab" data-toggle="pill" href="#pills-description" role="tab" aria-controls="pills-description" aria-expanded="true">Description</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="pills-payment-tab" data-toggle="pill" href="#pills-payment" role="tab" aria-controls="pills-payment" aria-expanded="true">Payment Methods</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="pills-comment-tab" data-toggle="pill" href="#pills-comment" role="tab" aria-controls="pills-comment" aria-expanded="true">Reviews</a>
                    </li>
                </ul>
                <div class="tab-content" id="pills-tabContent">
                    <div class="tab-pane fade show active" id="pills-description" role="tabpanel" aria-labelledby="pills-description-tab">
                        <p>Consequat occaecat ullamco amet non eiusmod nostrud dolore irure incididunt est duis anim sunt officia. Fugiat velit proident aliquip nisi incididunt nostrud exercitation proident est nisi. Irure magna elit commodo anim ex veniam culpa eiusmod id nostrud sit cupidatat in veniam ad. Eiusmod consequat eu adipisicing minim anim aliquip cupidatat culpa excepteur quis. Occaecat sit eu exercitation irure Lorem incididunt nostrud.</p>
                    </div>
                    <div class="tab-pane fade" id="pills-payment" role="tabpanel" aria-labelledby="pills-payment-tab">
                        <p>Ad pariatur nostrud pariatur exercitation ipsum ipsum culpa mollit commodo mollit ex. Aute sunt incididunt amet commodo est sint nisi deserunt pariatur do. Aliquip ex eiusmod voluptate exercitation cillum id incididunt elit sunt. Qui minim sit magna Lorem id et dolore velit Lorem amet exercitation duis deserunt. Anim id labore elit adipisicing ut in id occaecat pariatur ut ullamco ea tempor duis.</p>
                    </div>
                    <div class="tab-pane fade" id="pills-comment" role="tabpanel" aria-labelledby="pills-comment-tab">
                        <p>Est quis nulla laborum officia ad nisi ex nostrud culpa Lorem excepteur aliquip dolor aliqua irure ex. Nulla ut duis ipsum nisi elit fugiat commodo sunt reprehenderit laborum veniam eu veniam. Eiusmod minim exercitation fugiat irure ex labore incididunt do fugiat commodo aliquip sit id deserunt reprehenderit aliquip nostrud. Amet ex cupidatat excepteur aute veniam incididunt mollit cupidatat esse irure officia elit do ipsum ullamco Lorem. Ullamco ut ad minim do mollit labore ipsum laboris ipsum commodo sunt tempor enim incididunt. Commodo quis sunt dolore aliquip aute tempor irure magna enim minim reprehenderit. Ullamco consectetur culpa veniam sint cillum aliqua incididunt velit ullamco sunt ullamco quis quis commodo voluptate. Mollit nulla nostrud adipisicing aliqua cupidatat aliqua pariatur mollit voluptate voluptate consequat non.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- Yorumlar Bölümü -->
    <div class="row mt-5">
        <div class="col-md-12">
            <a href="/Comment/AddedComment/@Model.Product.Id" class="btn btn-primary btn-sm float-right">
                <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                Yorum Yaz
            </a>
            <h3>Comments</h3>

            @if (Model.Comment != null && Model.Comment.Any())
            {
                <ul class="list-unstyled">
                    @foreach (var comment in Model.Comment)
                    {
                        <li class="media mb-3">
                            <img src="~/theme/img/userImageProfile.jpg" class="mr-3 rounded-circle" alt="...">
                            <div class="media-body d-flex justify-content-between align-items-start">
                                <div>
                                    <h5 class="mt-0 mb-1">@comment.UserId</h5>
                                    <p>@comment.UserComment</p>
                                </div>

                                @if (Session["UserId"] as string == comment.UserId)
                                {
                                    <form method="post" action="@Url.Action("DeleteComment", "Comment")">
                                        @Html.Hidden("commentId", comment.Id)
                                        <button type="submit" class="btn btn-danger">
                                            Sil
                                        </button>
                                    </form>
                                }
                            </div>
                        </li>
                    }
                </ul>
            }
            else
            {
                <p>No comments available.</p>
            }
        </div>
    </div>



</div>

Abc.Mvc/Abc.Mvc/Views/Home/GetCategories.cshtml
@model IEnumerable<Abc.Mvc.Entity.Category>
@{ 
    var selectedCategory = Url.RequestContext.RouteData.Values["id"];
}
<ul class="list-group">

    <a href="/Home/List" class="list-group-item">
        <i class="fa fa-angle-double-right" aria-hidden="true"></i>
        Tüm Kategoriler
    </a>

    @foreach (var item in Model)
    {
        if (selectedCategory != null)
        {
            if (item.Id == int.Parse(selectedCategory.ToString()))
            {
                // seçilen katogori ile route id si birbirine eşit


                <a href="/Home/List/@item.Id" class="list-group-item active">
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                    @item.Name
                </a>

            }
            else
            {

                <a href="/Home/List/@item.Id" class="list-group-item ">
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                    @item.Name
                </a>

            }
        }
        else
        {

            <a href="/Home/List/@item.Id" class="list-group-item ">
                <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                @item.Name
            </a>



        }


    }


</ul>

Abc.Mvc/Abc.Mvc/Views/Home/Index.cshtml
@using Abc.Mvc.Models;
@model IEnumerable<ProductModel>
@{
    ViewBag.Title = "Index";
}


<div class="jumbotron">

    <h1 class="display-3">Merhaba @Session["UserId"]</h1>
    <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <p class="lead">
        <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
    </p>

</div>

<div class="cantainer pb-5">

@Html.Partial("_ProductList", Model);

</div>

Abc.Mvc/Abc.Mvc/Views/Home/List.cshtml
@using Abc.Mvc.Models;
@model IEnumerable<ProductModel>
@{
    ViewBag.Title = "List";
}

    <div class="col-md-3">

        @Html.Action("GetCategories", "Home")
    </div>



    <div class="container pb-4">
        <div class="row">

            <div class="col-md-10">
               
                    @if (Model.Count() == 0)
                    {
                        <div class="alert alert-warning" role="alert">
                            <i class="fa fa-exclamation-circle" aria-hidden="true"></i>
                            Bu kategoride bir ürün bulunamadı.
                        </div>
                    }
                    else
                    {
                        <div class="alert alert-warning" role="alert">
                            <i class="fa fa-check-square" aria-hidden="true"></i>
                            <strong>@Model.Count()</strong>  adet ürün bulundu.
                        </div>
                    }
             
            </div>
            @Html.Partial("_ProductList", Model);
        </div>


    </div>